### PR TITLE
fix(Markers): remove clipping on android

### LINKED ISSUE #17: Does this module support Android?
It seems that it doesn't work great in Android.

### PR DESCRIPTION
**Pull request by iam4x**
fixes #17 #20 using @chung-nguyen solution

### CODE REVIEW

**Comment by l-urence** [comment]
Someone with access to the npm need to publish it.

**Comment by adambene** [comment]
continuous delivery solves the npm publish problem 👍

**Comment by jordanmkoncz** [comment]
@l-urence Any ETA on getting someone to publish a new version of the package to NPM? Currently this fix that's been merged can't be used unless you set up your package.json to download this specific commit and bypass NPM.

**Comment by cjcheshire** [comment]
@l-urence Would really love this released :).

**Pull request merged**
