### PR TITLE
Support for React Native >= 0.49

### PR DESCRIPTION
**Pull request by wkoutre**
Changed `View.propTypes` to first check for `ReactNative.ViewPropTypes` if user is on RN >= 0.49

### CODE REVIEW

**Comment by adamhaney** [comment]
I've been using this as a dependency pinned to @wkoutre's branch/commit and it's been working well for me, any reason to not merge this into the mainline?

**Comment by wkoutre** [comment]
Second to this. Just simple updates coinciding with React Native monthly releases, as well as a few other minor things.

**Comment by rafinskipg** [comment]
@JackDanielsAndCode please merge this

**Comment by rafinskipg** [comment]
@adamhaney  how did you point to @wkoutre  version? I'm trying with no luck, (if you can please provide a really dumb example)

I'm doing this: `"react-native-multi-slider": "git@github.com:wkoutre/react-native-multi-slider.git#469aca48c610394d66fab278622d0c33de992b11",` 
But yarn still tries to select one version

**Comment by wkoutre** [comment]
@rafinskipg You probably have to delete your `yarn.lock` file and reinstall your dependencies.

- `rm yarn.lock`
- (if you want) `rm -rf node_modules/`
- `yarn`

In my own projects’ package.json, I have this:

`react-native-multi-slider": "https://github.com/wkoutre/react-native-multi-slider"`

I’d create a separate npm package for it but... it hardly seems necessary considering this is such a simple PR.

**Comment by adamhaney** [comment]
@rafinskipg I'm doing this
```
    "react-native-multi-slider": "wkoutre/react-native-multi-slider#469aca4",
```

You might also want to follow the above advice of running rm -rf node_modules/ if you have any further trouble.

**Pull request closed without merging**
